/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewKaryawan;

import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUNITA
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        CardLayout cl = (CardLayout) (isiMenu.getLayout());

        isiMenu.add("dataObat", dataObat);
        isiMenu.add("tb_ObatUmum", tb_ObatUmum);
    }

    public void showCard(String key) {
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        dataobat = new javax.swing.JButton();
        datapelanggan = new javax.swing.JButton();
        laporanobat = new javax.swing.JButton();
        laporanpelanggan = new javax.swing.JButton();
        profil = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        isiMenu = new javax.swing.JPanel();
        dataObat = new javax.swing.JPanel();
        tabObat = new javax.swing.JTabbedPane();
        obatUmum = new javax.swing.JPanel();
        pilihan1 = new javax.swing.JComboBox<>();
        search1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelUmum = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();
        obatResep = new javax.swing.JPanel();
        tambah2 = new javax.swing.JButton();
        hapus2 = new javax.swing.JButton();
        ubah2 = new javax.swing.JButton();
        pilihan2 = new javax.swing.JComboBox<>();
        search2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelResep = new javax.swing.JTable();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        tb_ObatUmum = new javax.swing.JPanel();
        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        isi = new javax.swing.JTextField();
        namaobat = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        hargabeli = new javax.swing.JTextField();
        hargasatuan = new javax.swing.JTextField();
        hargabox = new javax.swing.JTextField();
        satuan = new javax.swing.JComboBox<>();
        kodeobat = new javax.swing.JTextField();
        ubahsimpan = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        b_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setLayout(null);

        dataobat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/obat.png"))); // NOI18N
        dataobat.setBorder(null);
        dataobat.setBorderPainted(false);
        dataobat.setContentAreaFilled(false);
        dataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataobatActionPerformed(evt);
            }
        });
        menu.add(dataobat);
        dataobat.setBounds(0, 0, 225, 77);

        datapelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/pelanggan.png"))); // NOI18N
        datapelanggan.setBorder(null);
        datapelanggan.setBorderPainted(false);
        datapelanggan.setContentAreaFilled(false);
        datapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datapelangganActionPerformed(evt);
            }
        });
        menu.add(datapelanggan);
        datapelanggan.setBounds(225, 0, 225, 77);

        laporanobat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/laporan obat.png"))); // NOI18N
        laporanobat.setBorder(null);
        laporanobat.setBorderPainted(false);
        laporanobat.setContentAreaFilled(false);
        laporanobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanobatActionPerformed(evt);
            }
        });
        menu.add(laporanobat);
        laporanobat.setBounds(450, 0, 225, 77);

        laporanpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/laporan pelanggan.png"))); // NOI18N
        laporanpelanggan.setBorder(null);
        laporanpelanggan.setBorderPainted(false);
        laporanpelanggan.setContentAreaFilled(false);
        laporanpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanpelangganActionPerformed(evt);
            }
        });
        menu.add(laporanpelanggan);
        laporanpelanggan.setBounds(675, 0, 225, 77);

        profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/profil.png"))); // NOI18N
        profil.setBorder(null);
        profil.setBorderPainted(false);
        profil.setContentAreaFilled(false);
        profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilActionPerformed(evt);
            }
        });
        menu.add(profil);
        profil.setBounds(900, 0, 225, 77);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/logout.png"))); // NOI18N
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);
        logout.setBounds(1125, 0, 225, 77);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 77));

        isiMenu.setLayout(new java.awt.CardLayout());

        dataObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabObatMouseClicked(evt);
            }
        });

        obatUmum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pilihan1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Obat", "Nama Obat" }));
        obatUmum.add(pilihan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 220, 30));

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        search1.setBorder(null);
        search1.setBorderPainted(false);
        search1.setContentAreaFilled(false);
        obatUmum.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 18, 62, 40));

        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setBorder(null);
        obatUmum.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 270, 20));

        tabelUmum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelUmum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Obat", "Satuan", "Isi", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        tabelUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUmumMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelUmum);

        obatUmum.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah.setBorder(null);
        tambah.setBorderPainted(false);
        tambah.setContentAreaFilled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        obatUmum.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 9, 130, 50));

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah.setBorder(null);
        ubah.setBorderPainted(false);
        ubah.setContentAreaFilled(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        obatUmum.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 11, -1, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus.setBorder(null);
        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        obatUmum.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1198, 9, -1, 50));

        kembali.setText("kembali");
        obatUmum.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer obat.png"))); // NOI18N
        obatUmum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 540));

        tabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Satuan", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        jScrollPane3.setViewportView(tabel2);

        obatUmum.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer2.png"))); // NOI18N
        obatUmum.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        tabObat.addTab("Obat Umum", obatUmum);

        obatResep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah2.setBorder(null);
        tambah2.setBorderPainted(false);
        tambah2.setContentAreaFilled(false);
        tambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah2ActionPerformed(evt);
            }
        });
        obatResep.add(tambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 139, 130, 50));

        hapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus2.setBorder(null);
        hapus2.setBorderPainted(false);
        hapus2.setContentAreaFilled(false);
        obatResep.add(hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 331, 130, 50));

        ubah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah2.setBorder(null);
        ubah2.setBorderPainted(false);
        ubah2.setContentAreaFilled(false);
        ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah2ActionPerformed(evt);
            }
        });
        obatResep.add(ubah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 235, 130, 50));

        pilihan2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Resep", "Nama Resep" }));
        obatResep.add(pilihan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, 30));

        search2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari_1.png"))); // NOI18N
        search2.setContentAreaFilled(false);
        obatResep.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 30, 30));

        tabelResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Kode Resep", "Nama Resep"
            }
        ));
        jScrollPane1.setViewportView(tabelResep);

        obatResep.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 57, 1030, 460));

        txt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2.setBorder(null);
        obatResep.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 15, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/obatt.png"))); // NOI18N
        obatResep.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 540));

        tabObat.addTab("Obat Beresep", obatResep);

        dataObat.add(tabObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 570));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blank.png"))); // NOI18N
        dataObat.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataObat, "card2");

        tb_ObatUmum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/batal.png"))); // NOI18N
        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        tb_ObatUmum.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1179, 473, 140, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        tb_ObatUmum.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 472, 140, -1));

        isi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isi.setBorder(null);
        isi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiKeyTyped(evt);
            }
        });
        tb_ObatUmum.add(isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 233, 410, 38));

        namaobat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namaobat.setBorder(null);
        tb_ObatUmum.add(namaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 105, 409, 38));

        stok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stok.setBorder(null);
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stokKeyTyped(evt);
            }
        });
        tb_ObatUmum.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 296, 410, 38));

        hargabeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargabeli.setBorder(null);
        hargabeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargabeliKeyTyped(evt);
            }
        });
        tb_ObatUmum.add(hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 359, 410, 38));

        hargasatuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargasatuan.setBorder(null);
        hargasatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargasatuanKeyTyped(evt);
            }
        });
        tb_ObatUmum.add(hargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 422, 410, 38));

        hargabox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargabox.setBorder(null);
        hargabox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaboxKeyTyped(evt);
            }
        });
        tb_ObatUmum.add(hargabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 486, 410, 38));

        tb_ObatUmum.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 410, 38));

        kodeobat.setBorder(null);
        tb_ObatUmum.add(kodeobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 39, 408, 38));

        ubahsimpan.setBorder(null);
        ubahsimpan.setContentAreaFilled(false);
        tb_ObatUmum.add(ubahsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 472, 140, 63));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambahObat_1.png"))); // NOI18N
        tb_ObatUmum.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        isiMenu.add(tb_ObatUmum, "card3");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/lihat resep.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        isiMenu.add(jPanel1, "card4");

        getContentPane().add(isiMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 1350, 572));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer2.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1351, 690));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 690));

        b_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        getContentPane().add(b_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 572));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obatListener(ActionListener listener) {
        dataobat.addActionListener(listener);
    }

    public void pelangganListener(ActionListener listener) {
        datapelanggan.addActionListener(listener);
    }

    public void laporanObatListener(ActionListener listener) {
        laporanobat.addActionListener(listener);
    }

    public void laporanPelangganListener(ActionListener listener) {
        laporanpelanggan.addActionListener(listener);
    }

    public void profilListener(ActionListener listener) {
        profil.addActionListener(listener);
    }

    public void logoutListener(ActionListener listener) {
        logout.addActionListener(listener);
    }

    public JButton ObatButton() {
        return dataobat;
    }

    //obatUmum
    public void SearchObatUmum(ActionListener l) {
        this.search1.addActionListener(l);
    }

    public JTable getTabelObatUmum() {
        return tabelUmum;
    }

    public int getBarisObatUmum() {
        return tabelUmum.getSelectedRow();
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelUmum.setModel(tabel);
    }

    public void tabelListener(MouseListener m) {
        tabelUmum.addMouseListener(m);
    }

    public JComboBox getPilihan1() {
        return pilihan1;
    }

    public void setPilihan1(String pilihan1) {
        getPilihan1().addItem(pilihan1);
    }

    public JTextField settxtsearch1() {
        return txt1;
    }

    public String gettxtsearch1() {
        return txt1.getText();
    }

    public void TambahObatUmumListener(ActionListener e) {
        this.tambah.addActionListener(e);
    }

    public void UbahObatUmumListener(ActionListener e) {
        this.ubah.addActionListener(e);
    }

    public void HapusObatUmumListener(ActionListener e) {
        this.hapus.addActionListener(e);
    }

    public void searchListener(ActionListener e) {
        this.search1.addActionListener(e);
    }

    public void kembaliListener(ActionListener l) {
        this.kembali.addActionListener(l);
    }

    public JButton tambahObatUmum() {
        return tambah;
    }

    public JButton getUbah() {
        return ubah;
    }

    public JButton getHapus() {
        return hapus;
    }

    public JButton getSearch() {
        return search1;
    }

    public void buttonUbah(boolean status) {
        this.ubah.setEnabled(status);
    }

    public void buttonHapus(boolean status) {
        this.hapus.setEnabled(status);
    }

    public void buttonTambah(boolean status) {
        this.tambah.setEnabled(status);
    }

    //obat beresep
    public JTable getTabelObatBeresep() {
        return tabelResep;
    }

    public int getBaris2() {
        return tabelResep.getSelectedRow();
    }

    public void setTabel2(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }

    public void tabelResepListener(MouseListener m) {
        tabelResep.addMouseListener(m);
    }

    public JComboBox getPilihan2() {
        return pilihan2;
    }

    public void setPilihan2(String pilihan1) {
        getPilihan2().addItem(pilihan1);
    }

    public JTextField settxtsearch2() {
        return txt2;
    }

    public String gettxtsearch2() {
        return txt2.getText();
    }

    public void Tambah2Listener(ActionListener e) {
        this.tambah2.addActionListener(e);
    }

    public void Ubah2Listener(ActionListener e) {
        this.ubah2.addActionListener(e);
    }

    public void Hapus2Listener(ActionListener e) {
        this.hapus2.addActionListener(e);
    }

    public void search2Listener(ActionListener e) {
        this.search2.addActionListener(e);
    }

    public JButton getTambah2() {
        return tambah2;
    }

    public JButton getUbah2() {
        return ubah2;
    }

    public JButton getHapus2() {
        return hapus2;
    }

    public JButton getSearch2() {
        return search2;
    }

    //tambah obat umum
    public void simpanObatUmum(ActionListener e) {
        this.simpan.addActionListener(e);
    }

    public JButton simpan() {
        return simpan;
    }

    public JButton batal() {
        return batal;
    }

    public String getNamaObat() {
        return namaobat.getText();
    }

    public JComboBox getSatuan() {
        return satuan;
    }

    public void setSatuan(String satuan) {
        getSatuan().addItem(satuan);
    }

    public void setComboBox_Satuan(String[] satuan) {
        for (String a : satuan) {
            this.satuan.addItem(a);
        }
    }

    public String getStok() {
        return stok.getText();
    }

    public String getIsi() {
        return isi.getText();
    }

    public String getHargaBeli() {
        return hargabeli.getText();
    }

    public String getHargaBox() {
        return hargabox.getText();
    }

    public String getHargaSatuan() {
        return hargasatuan.getText();
    }

    public String getKode() {
        return kodeobat.getText();
    }

    public JTextField setkodeObat() {
        return kodeobat;
    }

    public JTextField setNamaObat() {
        return namaobat;
    }

    public JTextField setIsi() {
        return isi;
    }

    public JTextField setStok() {
        return stok;
    }

    public JTextField setHargaBeli() {
        return hargabeli;
    }

    public JTextField setHargaSatuan() {
        return hargasatuan;
    }

    public JTextField setHargaBox() {
        return hargabox;
    }

    public void setKode(String value) {
        this.kodeobat.setText(value);
    }

    public void setIsi(String value) {
        this.isi.setText(value);
    }

    public void setNama(String value) {
        this.namaobat.setText(value);
    }

    public void setStok(String value) {
        this.stok.setText(value);
    }

    public void setHargaBeli(String value) {
        this.hargabeli.setText(value);
    }

    public void setHargaSatuan(String value) {
        this.hargasatuan.setText(value);
    }

    public void setHargaBox(String value) {
        this.hargabox.setText(value);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabelUmum.getValueAt(baris, kolom);
    }

    public JButton ubahSimpan() {
        return ubahsimpan;
    }
    private void dataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataobatActionPerformed
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, "");
    }//GEN-LAST:event_dataobatActionPerformed

    private void datapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datapelangganActionPerformed

    }//GEN-LAST:event_datapelangganActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int close = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?", "Pesan keluar", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void laporanobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanobatActionPerformed

    }//GEN-LAST:event_laporanobatActionPerformed

    private void laporanpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanpelangganActionPerformed

    }//GEN-LAST:event_laporanpelangganActionPerformed

    private void profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilActionPerformed

    }//GEN-LAST:event_profilActionPerformed

    private void tabelUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUmumMouseClicked

    }//GEN-LAST:event_tabelUmumMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed

    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed

    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed

    }//GEN-LAST:event_hapusActionPerformed

    private void tambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah2ActionPerformed

    }//GEN-LAST:event_tambah2ActionPerformed

    private void ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah2ActionPerformed

    }//GEN-LAST:event_ubah2ActionPerformed

    private void tabObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabObatMouseClicked

    }//GEN-LAST:event_tabObatMouseClicked

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed

    }//GEN-LAST:event_batalActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed

    }//GEN-LAST:event_simpanActionPerformed

    private void isiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiKeyTyped

    }//GEN-LAST:event_isiKeyTyped

    private void stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyTyped

    }//GEN-LAST:event_stokKeyTyped

    private void hargabeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargabeliKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabeliKeyTyped

    private void hargasatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargasatuanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargasatuanKeyTyped

    private void hargaboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaboxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaboxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    private JPanel panel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_menu;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JButton batal;
    private javax.swing.JPanel dataObat;
    private javax.swing.JButton dataobat;
    private javax.swing.JButton datapelanggan;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus2;
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField hargabox;
    private javax.swing.JTextField hargasatuan;
    private javax.swing.JTextField isi;
    private javax.swing.JPanel isiMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kodeobat;
    private javax.swing.JButton laporanobat;
    private javax.swing.JButton laporanpelanggan;
    private javax.swing.JButton logout;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField namaobat;
    private javax.swing.JPanel obatResep;
    private javax.swing.JPanel obatUmum;
    private javax.swing.JComboBox<String> pilihan1;
    private javax.swing.JComboBox<String> pilihan2;
    private javax.swing.JButton profil;
    private javax.swing.JComboBox<String> satuan;
    private javax.swing.JButton search1;
    private javax.swing.JButton search2;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JTabbedPane tabObat;
    private javax.swing.JTable tabel2;
    private javax.swing.JTable tabelResep;
    private javax.swing.JTable tabelUmum;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tambah2;
    private javax.swing.JPanel tb_ObatUmum;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JButton ubah;
    private javax.swing.JButton ubah2;
    private javax.swing.JButton ubahsimpan;
    // End of variables declaration//GEN-END:variables
}
