/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewKaryawan;

/**
 *
 * @author JUNITA
 */
public class tambahObat2 extends javax.swing.JPanel {

    /**
     * Creates new form tambahObat2
     */
    public tambahObat2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stok = new javax.swing.JTextField();
        hargabox = new javax.swing.JTextField();
        hargasatuan = new javax.swing.JTextField();
        namaobat = new javax.swing.JTextField();
        background2 = new javax.swing.JLabel();
        ubahsimpan = new javax.swing.JButton();
        isi = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        satuan = new javax.swing.JComboBox<>();
        hargabeli = new javax.swing.JTextField();
        batal = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        stok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stok.setBorder(null);
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stokKeyTyped(evt);
            }
        });
        add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 270, 411, 38));

        hargabox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargabox.setBorder(null);
        hargabox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaboxKeyTyped(evt);
            }
        });
        add(hargabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 459, 411, 39));

        hargasatuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargasatuan.setBorder(null);
        hargasatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargasatuanKeyTyped(evt);
            }
        });
        add(hargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 396, 411, 39));

        namaobat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namaobat.setBorder(null);
        add(namaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 79, 411, 38));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambahObat_1.png"))); // NOI18N
        add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        ubahsimpan.setBorder(null);
        ubahsimpan.setContentAreaFilled(false);
        add(ubahsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 472, 140, 63));

        isi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isi.setBorder(null);
        isi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiKeyTyped(evt);
            }
        });
        add(isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 207, 410, 38));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 468, 140, -1));

        add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 144, 411, 38));

        hargabeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargabeli.setBorder(null);
        hargabeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargabeliKeyTyped(evt);
            }
        });
        add(hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 333, 411, 38));

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/batal.png"))); // NOI18N
        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 469, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyTyped

    }//GEN-LAST:event_stokKeyTyped

    private void hargaboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaboxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaboxKeyTyped

    private void hargasatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargasatuanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargasatuanKeyTyped

    private void isiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiKeyTyped

    }//GEN-LAST:event_isiKeyTyped

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed

    }//GEN-LAST:event_simpanActionPerformed

    private void hargabeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargabeliKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabeliKeyTyped

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed

    }//GEN-LAST:event_batalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background2;
    private javax.swing.JButton batal;
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField hargabox;
    private javax.swing.JTextField hargasatuan;
    private javax.swing.JTextField isi;
    private javax.swing.JTextField namaobat;
    private javax.swing.JComboBox<String> satuan;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JButton ubahsimpan;
    // End of variables declaration//GEN-END:variables
}
