/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewKaryawan;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author JUNITA
 */
public class tambahObat extends javax.swing.JFrame {

    /**
     * Creates new form tambahObat
     */
    public tambahObat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        isi = new javax.swing.JTextField();
        satuan = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        hargaBeli = new javax.swing.JTextField();
        hargasatuan = new javax.swing.JTextField();
        hargaBox = new javax.swing.JTextField();
        kode = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/batal.png"))); // NOI18N
        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 600, 140, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, 140, -1));

        isi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isi.setBorder(null);
        isi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiKeyTyped(evt);
            }
        });
        getContentPane().add(isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 410, 45));

        satuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        satuan.setBorder(null);
        satuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                satuanKeyTyped(evt);
            }
        });
        getContentPane().add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 205, 410, 45));

        nama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nama.setBorder(null);
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 127, 410, 45));

        stok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stok.setBorder(null);
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stokKeyTyped(evt);
            }
        });
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 356, 410, 45));

        hargaBeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargaBeli.setBorder(null);
        hargaBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaBeliKeyTyped(evt);
            }
        });
        getContentPane().add(hargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 433, 410, 45));

        hargasatuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargasatuan.setBorder(null);
        hargasatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargasatuanKeyTyped(evt);
            }
        });
        getContentPane().add(hargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 508, 410, 45));

        hargaBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargaBox.setBorder(null);
        hargaBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaBoxKeyTyped(evt);
            }
        });
        getContentPane().add(hargaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 583, 410, 45));
        getContentPane().add(kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 47, 410, 45));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambahobat.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        new dataObat().setVisible(true); 
        dispose();// TODO add your handling code here:j
    }//GEN-LAST:event_batalActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        new dataObat().setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void satuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_satuanKeyTyped
        char satuan = evt.getKeyChar();
        if (!(Character.isAlphabetic(satuan)
                ||(satuan==KeyEvent.VK_BACK_SPACE)
                ||(satuan==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Masukkan karakter huruf");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_satuanKeyTyped

    private void isiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiKeyTyped
             char isi = evt.getKeyChar();
        if (!(Character.isDigit(isi)
                ||(isi==KeyEvent.VK_BACK_SPACE)
                ||(isi==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");
                // TODO add your handling code here:
    }//GEN-LAST:event_isiKeyTyped
    }
    private void stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyTyped
               char stok = evt.getKeyChar();
        if (!(Character.isDigit(stok)
                ||(stok==KeyEvent.VK_BACK_SPACE)
                ||(stok==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");
                // TODO add your handling code here:
           // TODO add your handling code here:
    }//GEN-LAST:event_stokKeyTyped
    }
    private void hargaBeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaBeliKeyTyped
                  char hargaBeli = evt.getKeyChar();
        if (!(Character.isDigit(hargaBeli)
                ||(hargaBeli==KeyEvent.VK_BACK_SPACE)
                ||(hargaBeli==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");     // TODO add your handling code here:
    }//GEN-LAST:event_hargaBeliKeyTyped
    }
    private void hargasatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargasatuanKeyTyped
                  char hargasatuan = evt.getKeyChar();
        if (!(Character.isDigit(hargasatuan)
                ||(hargasatuan==KeyEvent.VK_BACK_SPACE)
                ||(hargasatuan==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");        // TODO add your handling code here:
    }//GEN-LAST:event_hargasatuanKeyTyped
    }
    private void hargaBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaBoxKeyTyped
                   char hargaBox = evt.getKeyChar();
        if (!(Character.isDigit(hargaBox)
                ||(hargaBox==KeyEvent.VK_BACK_SPACE)
                ||(hargaBox==KeyEvent.VK_DELETE)
                )) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");        // TODO add your handling code here:
    }     // TODO add your handling code here:
    }//GEN-LAST:event_hargaBoxKeyTyped
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton batal;
    private javax.swing.JTextField hargaBeli;
    private javax.swing.JTextField hargaBox;
    private javax.swing.JTextField hargasatuan;
    private javax.swing.JTextField isi;
    private javax.swing.JLabel kode;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField satuan;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    // End of variables declaration//GEN-END:variables
}
