/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewKasir;


import control.user;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.model_login;


/**
 *
 * @author JUNITA
 */
public class login extends javax.swing.JFrame {
    private user usr;
    private model_login loginn;
    public login() {
        initComponents();
        }
    
    public void loginListener(ActionListener a) {
        this.login.addActionListener(a);
    }
    public void resetListener(ActionListener a) {
        this.reset1.addActionListener(a);
    }
    public String getPassword() {
        String password = "";
        char passwordArray[] = this.txtpass.getPassword();
        for (int i = 0; i < passwordArray.length; i++) {
            password += passwordArray[i];
        }
        return password;
    }
    public void setPassword(String PasswordField_Password) {
        this.txtpass.setText(PasswordField_Password);
    }
    public String getUsername() {
        return txtuser.getText();
    }
    public void setUsername(String TextField_Username) {
        this.txtuser.setText(TextField_Username);
    }    
    public void pesanLogin(String pesan) {
        JOptionPane.showMessageDialog(this, pesan);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        reset1 = new javax.swing.JButton();
        login = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtuser.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtuser.setBorder(null);
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 337, 472, 25));

        txtpass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtpass.setBorder(null);
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 457, 472, 25));

        reset1.setForeground(new java.awt.Color(255, 255, 255));
        reset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/reset.png"))); // NOI18N
        reset1.setBorder(null);
        reset1.setBorderPainted(false);
        reset1.setContentAreaFilled(false);
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 555, 150, 60));

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/login.png"))); // NOI18N
        login.setBorder(null);
        login.setContentAreaFilled(false);
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 555, 150, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/layer1.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed

    }//GEN-LAST:event_reset1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton login;
    private javax.swing.JButton reset1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables

}
