/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewKasir;

import java.awt.CardLayout;
import java.awt.GridBagLayout;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUNITA
 */
public class menu extends javax.swing.JFrame {

    public menu() {
        initComponents();
        CardLayout cl = (CardLayout) (isiMenu.getLayout());

        isiMenu.add("dataObat", dataObat);
        isiMenu.add("mainMenu", mainMenu);
        isiMenu.add("datakas", datakas);
        isiMenu.add("dataTagihan", dataTagihan);
        isiMenu.add("dataPelanggan1", dataPelanggan1);
    }

    public void showCard(String key) {
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isiMenu = new javax.swing.JPanel();
        dataObat = new javax.swing.JPanel();
        tabObat = new javax.swing.JTabbedPane();
        obatUmum = new javax.swing.JPanel();
        menu5 = new javax.swing.JButton();
        pilihan1 = new javax.swing.JComboBox<>();
        search1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelUmum = new javax.swing.JTable();
        segarkann = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();
        obatResep = new javax.swing.JPanel();
        tambah2 = new javax.swing.JButton();
        hapus2 = new javax.swing.JButton();
        ubah2 = new javax.swing.JButton();
        pilihan2 = new javax.swing.JComboBox<>();
        search2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelResep = new javax.swing.JTable();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        obat = new javax.swing.JButton();
        pelanggan = new javax.swing.JButton();
        tagihan = new javax.swing.JButton();
        kas = new javax.swing.JButton();
        background6 = new javax.swing.JLabel();
        datakas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelkas = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        menu4 = new javax.swing.JButton();
        segarkan = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        dataPelanggan1 = new javax.swing.JPanel();
        menu2 = new javax.swing.JButton();
        segarkan2 = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        search7 = new javax.swing.JButton();
        tambah3 = new javax.swing.JButton();
        ubah1 = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        pelanggan1 = new javax.swing.JTable();
        background5 = new javax.swing.JLabel();
        dataTagihan = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabeltagihan = new javax.swing.JTable();
        cetak3 = new javax.swing.JCheckBox();
        txtkode3 = new javax.swing.JTextField();
        bayar3 = new javax.swing.JTextField();
        total3 = new javax.swing.JLabel();
        kembali4 = new javax.swing.JLabel();
        simpan3 = new javax.swing.JButton();
        kode3 = new javax.swing.JTextField();
        jumlah1 = new javax.swing.JTextField();
        tampilkan = new javax.swing.JButton();
        menu3 = new javax.swing.JButton();
        txtPelanggan = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        tgl = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isiMenu.setLayout(new java.awt.CardLayout());

        dataObat.setPreferredSize(new java.awt.Dimension(1349, 574));
        dataObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabObatMouseClicked(evt);
            }
        });

        obatUmum.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu5.setText("menu");
        obatUmum.add(menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 90, 30));

        pilihan1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Obat", "Nama Obat" }));
        obatUmum.add(pilihan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 25, 220, 30));

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        search1.setBorder(null);
        search1.setBorderPainted(false);
        search1.setContentAreaFilled(false);
        obatUmum.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 18, 62, 40));

        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setBorder(null);
        obatUmum.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 270, 20));

        tabelUmum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelUmum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Obat", "Satuan", "Isi", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        tabelUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUmumMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelUmum);

        obatUmum.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        segarkann.setText("Segarkan");
        obatUmum.add(segarkann, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer obat.png"))); // NOI18N
        obatUmum.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 540));

        tabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Satuan", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        jScrollPane3.setViewportView(tabel2);

        obatUmum.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer2.png"))); // NOI18N
        obatUmum.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        tabObat.addTab("Obat Umum", obatUmum);

        obatResep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah2.setBorder(null);
        tambah2.setBorderPainted(false);
        tambah2.setContentAreaFilled(false);
        tambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah2ActionPerformed(evt);
            }
        });
        obatResep.add(tambah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 139, 130, 50));

        hapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus2.setBorder(null);
        hapus2.setBorderPainted(false);
        hapus2.setContentAreaFilled(false);
        obatResep.add(hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 331, 130, 50));

        ubah2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah2.setBorder(null);
        ubah2.setBorderPainted(false);
        ubah2.setContentAreaFilled(false);
        ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah2ActionPerformed(evt);
            }
        });
        obatResep.add(ubah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 235, 130, 50));

        pilihan2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Resep", "Nama Resep" }));
        obatResep.add(pilihan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 170, 30));

        search2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari_1.png"))); // NOI18N
        search2.setContentAreaFilled(false);
        obatResep.add(search2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 30, 30));

        tabelResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode Resep", "Nama Resep"
            }
        ));
        jScrollPane1.setViewportView(tabelResep);

        obatResep.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 57, 1030, 460));

        txt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt2.setBorder(null);
        obatResep.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 15, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/obatt.png"))); // NOI18N
        obatResep.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 540));

        tabObat.addTab("Obat Beresep", obatResep);

        dataObat.add(tabObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 570));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blank.png"))); // NOI18N
        dataObat.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataObat, "card2");

        mainMenu.setPreferredSize(new java.awt.Dimension(1350, 574));
        mainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/obat.png"))); // NOI18N
        obat.setBorder(null);
        obat.setBorderPainted(false);
        obat.setContentAreaFilled(false);
        obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatActionPerformed(evt);
            }
        });
        mainMenu.add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/pelanggan.png"))); // NOI18N
        pelanggan.setBorder(null);
        pelanggan.setBorderPainted(false);
        pelanggan.setContentAreaFilled(false);
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        mainMenu.add(pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        tagihan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/tagihan.png"))); // NOI18N
        tagihan.setBorder(null);
        tagihan.setBorderPainted(false);
        tagihan.setContentAreaFilled(false);
        tagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagihanActionPerformed(evt);
            }
        });
        mainMenu.add(tagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        kas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/kas.png"))); // NOI18N
        kas.setBorder(null);
        kas.setBorderPainted(false);
        kas.setContentAreaFilled(false);
        kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasActionPerformed(evt);
            }
        });
        mainMenu.add(kas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        mainMenu.add(background6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(mainMenu, "card8");

        datakas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelkas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No. Transaksi", "Tanggal", "Pelanggan", "Kode Item", "Nama Item", "Jumlah", "Satuan", "Harga", "Sub Total", "Pegawai"
            }
        ));
        jScrollPane4.setViewportView(tabelkas);

        datakas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 67, 1290, 410));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelanggan Umum", "Pelanggan Beresep" }));
        datakas.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret ", "April", "Mei", "Juni", "Juli ", "Agustus", "September", "Oktober", "November", "Desember" }));
        datakas.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 140, 30));

        menu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu4.setText("Menu");
        datakas.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 40));

        segarkan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segarkan.setText("Segarkan");
        datakas.add(segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 100, 40));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        datakas.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(datakas, "card5");

        dataPelanggan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu2.setText("menu");
        dataPelanggan1.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 90, 30));

        segarkan2.setText("Segarkan");
        dataPelanggan1.add(segarkan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 530, 90, 30));

        txt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt3.setBorder(null);
        dataPelanggan1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 17, 270, 34));

        search7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/search1.png"))); // NOI18N
        search7.setBorder(null);
        search7.setBorderPainted(false);
        search7.setContentAreaFilled(false);
        dataPelanggan1.add(search7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 62, 43));

        tambah3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah3.setBorder(null);
        tambah3.setBorderPainted(false);
        tambah3.setContentAreaFilled(false);
        tambah3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah3MouseClicked(evt);
            }
        });
        tambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah3ActionPerformed(evt);
            }
        });
        dataPelanggan1.add(tambah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 9, 130, 50));

        ubah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah1.setBorder(null);
        ubah1.setBorderPainted(false);
        ubah1.setContentAreaFilled(false);
        ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah1ActionPerformed(evt);
            }
        });
        dataPelanggan1.add(ubah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 11, -1, -1));

        hapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus1.setBorder(null);
        hapus1.setBorderPainted(false);
        hapus1.setContentAreaFilled(false);
        dataPelanggan1.add(hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1198, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Kode Pelanggan");
        dataPelanggan1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        pelanggan1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pelanggan", "Tanggal Daftar", "Nama Pelanggan", "Jenis Kelamin", "Tanggal Lahir", "Alamat", "No Telepon"
            }
        ));
        jScrollPane9.setViewportView(pelanggan1);

        dataPelanggan1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1290, 430));

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer2.png"))); // NOI18N
        dataPelanggan1.add(background5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataPelanggan1, "card5");

        dataTagihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabeltagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Item", "Nama Item", "Jumlah", "Satuan", "Harga", "Sub Total"
            }
        ));
        jScrollPane8.setViewportView(tabeltagihan);

        dataTagihan.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 750, 250));

        cetak3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cetak3.setSelected(true);
        cetak3.setText("  Cetak");
        cetak3.setContentAreaFilled(false);
        dataTagihan.add(cetak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 100, 40));

        txtkode3.setBorder(null);
        dataTagihan.add(txtkode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 270, 24));

        bayar3.setBorder(null);
        dataTagihan.add(bayar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 496, 226, 24));

        total3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataTagihan.add(total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 456, 226, 24));

        kembali4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataTagihan.add(kembali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 535, 226, 24));

        simpan3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        simpan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/simpan.png"))); // NOI18N
        simpan3.setBorder(null);
        simpan3.setBorderPainted(false);
        simpan3.setContentAreaFilled(false);
        dataTagihan.add(simpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 512, 130, 50));

        kode3.setBorder(null);
        dataTagihan.add(kode3, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 229, 248, 24));

        jumlah1.setBorder(null);
        jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah1ActionPerformed(evt);
            }
        });
        jumlah1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlah1KeyTyped(evt);
            }
        });
        dataTagihan.add(jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 276, 248, 24));

        tampilkan.setText("Tampilkan");
        dataTagihan.add(tampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        menu3.setText("menu");
        dataTagihan.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 90, 30));

        txtPelanggan.setBorder(null);
        dataTagihan.add(txtPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 260, 24));

        ok.setText("Ok");
        dataTagihan.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));
        dataTagihan.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 15, 264, 23));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/layer tagihan2.png"))); // NOI18N
        dataTagihan.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataTagihan, "card5");

        getContentPane().add(isiMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1349, 572));

        menu.setLayout(null);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/logout.png"))); // NOI18N
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);
        logout.setBounds(1125, 0, 225, 77);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer2.png"))); // NOI18N
        menu.add(jLabel3);
        jLabel3.setBounds(0, 0, 1349, 77);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 77));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obatListener(ActionListener listener) {
        obat.addActionListener(listener);
    }

    public void tagihanListener(ActionListener listener) {
        tagihan.addActionListener(listener);
    }

    public void kasListener(ActionListener listener) {
        kas.addActionListener(listener);
    }

    public void pelangganListener(ActionListener listener) {
        pelanggan.addActionListener(listener);
    }

    public void SearchObatUmum(ActionListener l) {
        this.search1.addActionListener(l);
    }

    public void Searchpelanggan(ActionListener l) {
        this.search7.addActionListener(l);
    }

    public JTable getTabelObatUmum() {
        return tabelUmum;
    }

    public int getBarisObatUmum() {
        return tabelUmum.getSelectedRow();
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelUmum.setModel(tabel);
    }

    public void tabelListener(MouseListener m) {
        tabelUmum.addMouseListener(m);
    }

    public JComboBox getPilihan1() {
        return pilihan1;
    }

    public void setPilihan1(String pilihan1) {
        getPilihan1().addItem(pilihan1);
    }

    public JTextField settxtsearch1() {
        return txt1;
    }

    public String gettxtsearch1() {
        return txt1.getText();
    }

    public void searchListener(ActionListener e) {
        this.search1.addActionListener(e);
    }

    public void segarkanListener2(ActionListener l) {
        this.segarkann.addActionListener(l);
    }

    public JButton getSearch() {
        return search1;
    }

    public JButton kembaliMenu4() {
        return menu2;
    }

    public JButton kembaliMenu() {
        return menu3;
    }

    public JButton kembaliMenu5() {
        return menu4;
    }

    public JButton kembaliMenu3() {
        return menu5;
    }

    public void tabelpelanggan(MouseListener m) {
        pelanggan1.addMouseListener(m);
    }

    public void setTabelpelanggan(DefaultTableModel tabel) {
        this.pelanggan1.setModel(tabel);
    }

    public void setTabeltagihan(DefaultTableModel tabel) {
        this.tabeltagihan.setModel(tabel);
    }

    public String gettxtsearch() {
        return txt3.getText();
    }

    public void segarkanListener(ActionListener l) {
        this.segarkan2.addActionListener(l);
    }

    public JTable gettabelpelanggan() {
        return pelanggan1;
    }

    public int getBaristabelpelanggan() {
        return pelanggan1.getSelectedRow();
    }

    public void settgl(String value) {
        this.tgl.setText(value);
    }

    public void setkodeResep(String value) {
        this.txtkode3.setText(value);
    }

    public void setPelanggan(String value) {
        this.txtPelanggan.setText(value);
    }

    public void setkodeitem(String value) {
        this.kode3.setText(value);
    }

    public void setjumlah(String value) {
        this.jumlah1.setText(value);
    }
    private void obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatActionPerformed
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, "");
    }//GEN-LAST:event_obatActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed

    }//GEN-LAST:event_pelangganActionPerformed

    private void tagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagihanActionPerformed

    }//GEN-LAST:event_tagihanActionPerformed

    private void kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasActionPerformed

    }//GEN-LAST:event_kasActionPerformed

    private void tabelUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUmumMouseClicked

    }//GEN-LAST:event_tabelUmumMouseClicked

    private void tambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah2ActionPerformed

    }//GEN-LAST:event_tambah2ActionPerformed

    private void ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah2ActionPerformed

    }//GEN-LAST:event_ubah2ActionPerformed

    private void tabObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabObatMouseClicked

    }//GEN-LAST:event_tabObatMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int close = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?", "Pesan keluar", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void tambah3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah3MouseClicked

    }//GEN-LAST:event_tambah3MouseClicked

    private void tambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah3ActionPerformed

    }//GEN-LAST:event_tambah3ActionPerformed

    private void ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubah1ActionPerformed

    private void jumlah1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah1KeyTyped
        char jumlah = evt.getKeyChar();
        if (!(Character.isDigit(jumlah)
                || (jumlah == KeyEvent.VK_BACK_SPACE)
                || (jumlah == KeyEvent.VK_DELETE))) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1KeyTyped

    private void jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JTextField bayar3;
    private javax.swing.JCheckBox cetak3;
    private javax.swing.JPanel dataObat;
    private javax.swing.JPanel dataPelanggan1;
    private javax.swing.JPanel dataTagihan;
    private javax.swing.JPanel datakas;
    private javax.swing.JButton hapus1;
    private javax.swing.JButton hapus2;
    private javax.swing.JPanel isiMenu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JButton kas;
    private javax.swing.JLabel kembali4;
    private javax.swing.JTextField kode3;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menu2;
    private javax.swing.JButton menu3;
    private javax.swing.JButton menu4;
    private javax.swing.JButton menu5;
    private javax.swing.JButton obat;
    private javax.swing.JPanel obatResep;
    private javax.swing.JPanel obatUmum;
    private javax.swing.JButton ok;
    private javax.swing.JButton pelanggan;
    private javax.swing.JTable pelanggan1;
    private javax.swing.JComboBox<String> pilihan1;
    private javax.swing.JComboBox<String> pilihan2;
    private javax.swing.JButton search1;
    private javax.swing.JButton search2;
    private javax.swing.JButton search7;
    private javax.swing.JButton segarkan;
    private javax.swing.JButton segarkan2;
    private javax.swing.JButton segarkann;
    private javax.swing.JButton simpan3;
    private javax.swing.JTabbedPane tabObat;
    private javax.swing.JTable tabel2;
    private javax.swing.JTable tabelResep;
    private javax.swing.JTable tabelUmum;
    private javax.swing.JTable tabelkas;
    private javax.swing.JTable tabeltagihan;
    private javax.swing.JButton tagihan;
    private javax.swing.JButton tambah2;
    private javax.swing.JButton tambah3;
    private javax.swing.JButton tampilkan;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel total3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txtPelanggan;
    private javax.swing.JTextField txtkode3;
    private javax.swing.JButton ubah1;
    private javax.swing.JButton ubah2;
    // End of variables declaration//GEN-END:variables
}
