/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewKasir;

/**
 *
 * @author JUNITA
 */
public class profil extends javax.swing.JPanel {

    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        kode4 = new javax.swing.JLabel();
        kode5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 152, 410, 40));
        add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 238, 410, 40));
        add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 320, 410, 40));
        add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 401, 410, 40));
        add(kode4, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 483, 410, 40));
        add(kode5, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 73, 410, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/profil.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel kode4;
    private javax.swing.JLabel kode5;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
