/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apotek;

/**
 *
 * @author JUNITA
 */
public class dataTagihan extends javax.swing.JPanel {

    /**
     * Creates new form dataTagihan
     */
    public dataTagihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cetak = new javax.swing.JCheckBox();
        txtTransaksi = new javax.swing.JTextField();
        txtPelanggan = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        namaPegawai = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        pegawai = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        bayar = new javax.swing.JTextField();
        discount = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        kembali = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Kode Item", "Nama Item", "Jumlah", "Satuan", "Harga", "Discount", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1310, 270));

        cetak.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cetak.setText("  Cetak");
        cetak.setContentAreaFilled(false);
        add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 100, 40));

        txtTransaksi.setBorder(null);
        add(txtTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 15, 275, 24));

        txtPelanggan.setBorder(null);
        add(txtPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 88, 248, 24));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Umum", "Resep" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 88, 155, 24));

        namaPegawai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaPegawai.setText("jLabel3");
        add(namaPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));
        add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 52, 275, 24));

        pegawai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pegawai.setText("Pegawai");
        add(pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/search.png"))); // NOI18N
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 86, 28, 28));

        bayar.setBorder(null);
        add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 496, 226, 24));

        discount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 456, 226, 24));

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 417, 226, 24));

        kembali.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 535, 226, 24));

        simpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/simpan.png"))); // NOI18N
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1206, 512, 130, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/layer2.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField bayar;
    private javax.swing.JCheckBox cetak;
    private javax.swing.JLabel discount;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel namaPegawai;
    private javax.swing.JLabel pegawai;
    private javax.swing.JButton search;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel total;
    private javax.swing.JTextField txtPelanggan;
    private javax.swing.JTextField txtTransaksi;
    // End of variables declaration//GEN-END:variables
}
