/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.model_login;

/**
 *
 * @author JUNITA
 */
public class menu_karyawan extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu_karyawan() {
        initComponents();

        CardLayout cl = (CardLayout) (isiMenu.getLayout());

        isiMenu.add("dataObat", dataObat);
        isiMenu.add("tb_ObatUmum", tb_Obat);
        isiMenu.add("mainMenu", mainMenu);
        isiMenu.add("laporanObat", laporanObat);
    }

    public void showCard(String key) {
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        sessionnama = new javax.swing.JLabel();
        sessionkode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        isiMenu = new javax.swing.JPanel();
        dataObat = new javax.swing.JPanel();
        menu2 = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        segarkan2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelUmum = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        search1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();
        tb_Obat = new javax.swing.JPanel();
        batal = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        namaobat = new javax.swing.JTextField();
        isi = new javax.swing.JTextField();
        stok = new javax.swing.JTextField();
        hargabeli = new javax.swing.JTextField();
        hargasatuan = new javax.swing.JTextField();
        hargabox = new javax.swing.JTextField();
        satuan = new javax.swing.JComboBox<>();
        ubahsimpan = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        background6 = new javax.swing.JLabel();
        laporanobat1 = new javax.swing.JButton();
        dataobat = new javax.swing.JButton();
        laporanObat = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        laporanobat = new javax.swing.JTable();
        tglcari = new com.toedter.calendar.JDateChooser();
        cari = new javax.swing.JButton();
        segarkan3 = new javax.swing.JButton();
        menulap = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        b_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setLayout(null);

        sessionnama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.add(sessionnama);
        sessionnama.setBounds(1030, 10, 220, 20);

        sessionkode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.add(sessionkode);
        sessionkode.setBounds(1030, 40, 210, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/Desain Billin Apotik2.png"))); // NOI18N
        menu.add(jLabel3);
        jLabel3.setBounds(0, 0, 1349, 77);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/logout.png"))); // NOI18N
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);
        logout.setBounds(1125, 0, 225, 77);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 77));

        isiMenu.setLayout(new java.awt.CardLayout());

        dataObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu2.setText("menu");
        dataObat.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 90, 30));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah.setBorder(null);
        tambah.setBorderPainted(false);
        tambah.setContentAreaFilled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        dataObat.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(928, 9, 130, 50));

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah.setBorder(null);
        ubah.setBorderPainted(false);
        ubah.setContentAreaFilled(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        dataObat.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 11, -1, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus.setBorder(null);
        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        dataObat.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1198, 9, -1, 50));

        segarkan2.setText("Segarkan");
        dataObat.add(segarkan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 90, 30));

        tabelUmum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelUmum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Obat", "Satuan", "Isi", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        tabelUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUmumMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelUmum);

        dataObat.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 1290, 410));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nama Obat");
        dataObat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 220, 30));

        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setBorder(null);
        dataObat.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 270, 20));

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        search1.setBorder(null);
        search1.setBorderPainted(false);
        search1.setContentAreaFilled(false);
        dataObat.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 18, 62, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer obat.png"))); // NOI18N
        dataObat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 540));

        tabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Satuan", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        jScrollPane3.setViewportView(tabel2);

        dataObat.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer2.png"))); // NOI18N
        dataObat.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataObat, "card2");

        tb_Obat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/batal.png"))); // NOI18N
        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        tb_Obat.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 469, 140, -1));

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        simpan.setBorder(null);
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        tb_Obat.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 468, 140, -1));

        namaobat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        namaobat.setBorder(null);
        tb_Obat.add(namaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 79, 411, 38));

        isi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        isi.setBorder(null);
        isi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiKeyTyped(evt);
            }
        });
        tb_Obat.add(isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 207, 410, 38));

        stok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        stok.setBorder(null);
        stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stokKeyTyped(evt);
            }
        });
        tb_Obat.add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 270, 411, 38));

        hargabeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargabeli.setBorder(null);
        hargabeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargabeliKeyTyped(evt);
            }
        });
        tb_Obat.add(hargabeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 333, 411, 38));

        hargasatuan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargasatuan.setBorder(null);
        hargasatuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargasatuanKeyTyped(evt);
            }
        });
        tb_Obat.add(hargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 396, 411, 39));

        hargabox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hargabox.setBorder(null);
        hargabox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaboxKeyTyped(evt);
            }
        });
        tb_Obat.add(hargabox, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 459, 411, 39));

        tb_Obat.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 144, 411, 38));

        ubahsimpan.setBorder(null);
        ubahsimpan.setContentAreaFilled(false);
        tb_Obat.add(ubahsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(997, 472, 140, 63));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambahObat_1.png"))); // NOI18N
        tb_Obat.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        isiMenu.add(tb_Obat, "card3");

        mainMenu.setPreferredSize(new java.awt.Dimension(1350, 574));
        mainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/main menu karyawan.png"))); // NOI18N
        mainMenu.add(background6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        laporanobat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/laporan obat.png"))); // NOI18N
        laporanobat1.setBorder(null);
        laporanobat1.setBorderPainted(false);
        laporanobat1.setContentAreaFilled(false);
        laporanobat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanobat1ActionPerformed(evt);
            }
        });
        mainMenu.add(laporanobat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 300, 200));

        dataobat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/obat.png"))); // NOI18N
        dataobat.setBorder(null);
        dataobat.setBorderPainted(false);
        dataobat.setContentAreaFilled(false);
        dataobat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataobatActionPerformed(evt);
            }
        });
        mainMenu.add(dataobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 300, 200));

        isiMenu.add(mainMenu, "card8");

        laporanObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laporanobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. ", "Tanggal", "Kode Obat", "Nama Obat", "Satuan", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        jScrollPane6.setViewportView(laporanobat);

        laporanObat.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1280, 410));

        tglcari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglcariPropertyChange(evt);
            }
        });
        laporanObat.add(tglcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 30));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        cari.setBorder(null);
        cari.setBorderPainted(false);
        cari.setContentAreaFilled(false);
        laporanObat.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 55, 30));

        segarkan3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segarkan3.setText("Segarkan");
        laporanObat.add(segarkan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 100, 40));

        menulap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menulap.setText("Menu");
        laporanObat.add(menulap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        laporanObat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(laporanObat, "card9");

        getContentPane().add(isiMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 1350, 572));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer2.png"))); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(1351, 690));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 690));

        b_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        getContentPane().add(b_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 572));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obatListener(ActionListener listener) {
        dataobat.addActionListener(listener);
    }

    public void laporanObatListener(ActionListener listener) {
        laporanobat1.addActionListener(listener);
    }

    public void logoutListener(ActionListener listener) {
        logout.addActionListener(listener);
    }

    public JButton ObatButton() {
        return dataobat;
    }

    public JButton kembaliMenu2() {
        return menu2;
    }

    public JTable getTabelObatUmum() {
        return tabelUmum;
    }

    public int getBarisObatUmum() {
        return tabelUmum.getSelectedRow();
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelUmum.setModel(tabel);
    }
    
        public void setTabel1(DefaultTableModel tabel) {
        this.laporanobat.setModel(tabel);
    }
        
            public void SearchObatUmum(ActionListener l) {
        this.search1.addActionListener(l);
    }
            
                public String gettxtsearch1() {
        return txt1.getText();
    }

    public void tabelListener(MouseListener m) {
        tabelUmum.addMouseListener(m);
    }

    public void setsessionnama(String sessionAdmin) {
        this.sessionnama.setText(sessionAdmin);
    }

    public void setsessionkode(String sessionAdmin) {
        this.sessionkode.setText(sessionAdmin);
    }

    public void TambahObatUmumListener(ActionListener e) {
        this.tambah.addActionListener(e);
    }

    public void UbahObatUmumListener(ActionListener e) {
        this.ubah.addActionListener(e);
    }

    public void HapusObatUmumListener(ActionListener e) {
        this.hapus.addActionListener(e);
    }

    public void segarkan2Listener(ActionListener l) {
        this.segarkan2.addActionListener(l);
    }

    public JButton tambahObatUmum() {
        return tambah;
    }

    public JButton getUbah() {
        return ubah;
    }

    public JButton getHapus() {
        return hapus;
    }

    public void buttonUbah(boolean status) {
        this.ubah.setEnabled(status);
    }

    public void buttonHapus(boolean status) {
        this.hapus.setEnabled(status);
    }

    public void buttonTambah(boolean status) {
        this.tambah.setEnabled(status);
    }

    public void setTabel2(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }

    public void carilistener(ActionListener l) {
        this.cari.addActionListener(l);
    }

    String Tanggal;

    public String GetTanggal() {
        return Tanggal;
    }
    
        public void carilistener1(ActionListener l) {
        this.cari.addActionListener(l);
    }

    //tambah obat 
    public void simpanObatUmum(ActionListener e) {
        this.simpan.addActionListener(e);
    }

    public JButton simpan() {
        return simpan;
    }

    public JButton batal() {
        return batal;
    }

    public String getNamaObat() {
        return namaobat.getText();
    }

    public JComboBox getSatuan() {
        return satuan;
    }

    public void setSatuan(String satuan) {
        getSatuan().addItem(satuan);
    }

    public void setComboBox_Satuan(String[] satuan) {
        for (String a : satuan) {
            this.satuan.addItem(a);
        }
    }

    public String getStok() {
        return stok.getText();
    }

    public String getIsi() {
        return isi.getText();
    }

    public String getHargaBeli() {
        return hargabeli.getText();
    }

    public String getHargaBox() {
        return hargabox.getText();
    }

    public String getHargaSatuan() {
        return hargasatuan.getText();
    }

    public JTextField setNamaObat() {
        return namaobat;
    }

    public JTextField setIsi() {
        return isi;
    }

    public JTextField setStok() {
        return stok;
    }

    public JTextField setHargaBeli() {
        return hargabeli;
    }

    public JTextField setHargaSatuan() {
        return hargasatuan;
    }

    public JTextField setHargaBox() {
        return hargabox;
    }

    public void setIsi(String value) {
        this.isi.setText(value);
    }

    public void setNama(String value) {
        this.namaobat.setText(value);
    }

    public void setStok(String value) {
        this.stok.setText(value);
    }

    public void setHargaBeli(String value) {
        this.hargabeli.setText(value);
    }

    public void setHargaSatuan(String value) {
        this.hargasatuan.setText(value);
    }

    public void setHargaBox(String value) {
        this.hargabox.setText(value);
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabelUmum.getValueAt(baris, kolom);
    }

    public JButton ubahSimpan() {
        return ubahsimpan;
    }

    public JButton kembaliMenu3() {
        return menulap;
    }

    public JButton kembaliMenu7() {
        return menu2;
    }

    public void segarkanlistener(ActionListener l) {
        this.segarkan2.addActionListener(l);
    }
    
       public void segarkanlistener2(ActionListener l) {
        this.segarkan3.addActionListener(l);
    }

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int close = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?", "Pesan keluar", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
//            System.exit(0);
            view.login login = new login();
            model.model_login model = null;
            try {
                model = new model_login();
            } catch (SQLException ex) {
                Logger.getLogger(menu_karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                new control.user(login, model);
            } catch (SQLException ex) {
                Logger.getLogger(menu_karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed

    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed

    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed

    }//GEN-LAST:event_hapusActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed

    }//GEN-LAST:event_batalActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed

    }//GEN-LAST:event_simpanActionPerformed

    private void isiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiKeyTyped

    }//GEN-LAST:event_isiKeyTyped

    private void stokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stokKeyTyped

    }//GEN-LAST:event_stokKeyTyped

    private void hargabeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargabeliKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargabeliKeyTyped

    private void hargasatuanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargasatuanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargasatuanKeyTyped

    private void hargaboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaboxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaboxKeyTyped

    private void dataobatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataobatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataobatActionPerformed

    private void laporanobat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanobat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporanobat1ActionPerformed

    private void tabelUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUmumMouseClicked

    }//GEN-LAST:event_tabelUmumMouseClicked

    private void tglcariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglcariPropertyChange
        if (tglcari.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Tanggal = sdf.format(tglcari.getDate());
            System.out.println(Tanggal);
        }
    }//GEN-LAST:event_tglcariPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_karyawan().setVisible(true);
            }
        });
    }
    private JPanel panel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_menu;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background6;
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JPanel dataObat;
    private javax.swing.JButton dataobat;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField hargabox;
    private javax.swing.JTextField hargasatuan;
    private javax.swing.JTextField isi;
    private javax.swing.JPanel isiMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel laporanObat;
    private javax.swing.JTable laporanobat;
    private javax.swing.JButton laporanobat1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menu2;
    private javax.swing.JButton menulap;
    private javax.swing.JTextField namaobat;
    private javax.swing.JComboBox<String> satuan;
    private javax.swing.JButton search1;
    private javax.swing.JButton segarkan2;
    private javax.swing.JButton segarkan3;
    private javax.swing.JLabel sessionkode;
    private javax.swing.JLabel sessionnama;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField stok;
    private javax.swing.JTable tabel2;
    private javax.swing.JTable tabelUmum;
    private javax.swing.JButton tambah;
    private javax.swing.JPanel tb_Obat;
    private com.toedter.calendar.JDateChooser tglcari;
    private javax.swing.JTextField txt1;
    private javax.swing.JButton ubah;
    private javax.swing.JButton ubahsimpan;
    // End of variables declaration//GEN-END:variables

}
