/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.model_login;

/**
 *
 * @author JUNITA
 */
public class menu_pemilik extends javax.swing.JFrame {

    public menu_pemilik() {
        initComponents();
        CardLayout cl = (CardLayout) (isimenu.getLayout());

        isimenu.add("datapegawai", datapegawai);
        isimenu.add("tb_datapegawai", tb_datapegawai);
        isimenu.add("laporankas", laporankas);
        isimenu.add("mainMenu", mainMenu);
        isimenu.add("laporanObat", laporanObat);
    }

    public void showCard(String key) {
        CardLayout cl = (CardLayout) (isimenu.getLayout());
        cl.show(isimenu, key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void datapegawaiListener(ActionListener listener) {
        pegawai.addActionListener(listener);
    }

    public void datakasListener(ActionListener listener) {
        kas.addActionListener(listener);
    }

    public void setsessionnama(String sessionAdmin) {
        this.sessionnama.setText(sessionAdmin);
    }

    public void setsessionkode(String sessionAdmin) {
        this.sessionkode.setText(sessionAdmin);
    }

    public void laporanObatListener(ActionListener listener) {
        obat.addActionListener(listener);
    }

    public void logoutListener(ActionListener listener) {
        logout.addActionListener(listener);
    }

    public JButton pegawaiButton() {
        return pegawai;
    }

    //datapegawai
    public JTable gettabelpegawai() {
        return tabelpegawai;
    }

    public JButton batal() {
        return batal;
    }

    public JButton kembaliMenu() {
        return menu2;
    }

    public int getBaristabelpegawai() {
        return tabelpegawai.getSelectedRow();
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelpegawai.setModel(tabel);
    }

    public void tabelpegawai(MouseListener m) {
        tabelpegawai.addMouseListener(m);
    }

    public void TambahpegawaiListener(ActionListener e) {
        this.tambah.addActionListener(e);
    }

    public void UbahpegawaiListener(ActionListener e) {
        this.ubah.addActionListener(e);
    }

    public void HapuspegawaiListener(ActionListener e) {
        this.hapus.addActionListener(e);
    }

    public JButton tambahpegawai() {
        return tambah;
    }

    public JButton getUbahpegawai() {
        return ubah;
    }

    public JButton getHapuspegawai() {
        return hapus;
    }

    public void carilistener(ActionListener l) {
        this.cari.addActionListener(l);
    }

    public void cari1listener(ActionListener l) {
        this.cari1.addActionListener(l);
    }

    public void buttonUbahpegawai(boolean status) {
        this.ubah.setEnabled(status);
    }

    public void buttonHapuspegawai(boolean status) {
        this.hapus.setEnabled(status);
    }

    public void buttonTambahpegawai(boolean status) {
        this.tambah.setEnabled(status);
    }

    //tambah pegawai
    public JDateChooser tanggalLahir() {
        return tgllahir;
    }

    public String getTanggallahir() {

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String tanggal = dateFormat.format(tgllahir.getDate());
        return tanggal;
    }

    public void setTgllahir(JDateChooser tgllahir) {
        this.tgllahir = tgllahir;
    }

    public void setComboBox_jabatan(String[] jabatan) {
        for (String a : jabatan) {
            this.jabatan.addItem(a);
        }
    }

    public void setComboBox_jeniskelamin(String[] jeniskelamin) {
        for (String a : jeniskelamin) {
            this.jeniskelamin.addItem(a);
        }
    }

    public void setNama(String value) {
        this.nama.setText(value);
    }

    public void setUser(String value) {
        this.user.setText(value);
    }

    public void setPass(String value) {
        this.pass.setText(value);
    }

    public void setAlamat(String value) {
        this.alamat.setText(value);
    }

    public void setNotelp(String value) {
        this.telp.setText(value);
    }

    public JTextField setnamapegawai() {
        return nama;
    }

    public JTextField setalamat() {
        return alamat;
    }

    public JTextField setnotelp() {
        return telp;
    }

    public JTextField setUserr() {
        return user;
    }

    public JTextField setPassw() {
        return pass;
    }

    public JComboBox getJabatan() {
        return jabatan;
    }

    public JComboBox getJeniskelamin() {
        return jeniskelamin;
    }

    public JButton ubahSimpanpegawai() {
        return ubahsimpan;
    }

    public JButton simpanpegawai() {
        return Simpan;
    }

    public String getNamaPegawai() {
        return nama.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public String getNotelp() {
        return telp.getText();
    }

    public String getUser() {
        return user.getText();
    }

    String Tanggal;

    public String GetTanggal() {
        return Tanggal;
    }

    String Tanggal1;

    public String GetTanggal1() {
        return Tanggal1;
    }

    public String getPass() {
        return pass.getText();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabelpegawai.getValueAt(baris, kolom);
    }

    public JButton kembaliMenu3() {
        return menulap;
    }

    public JButton kembaliMenu4() {
        return menu4;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        sessionnama = new javax.swing.JLabel();
        sessionkode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        isimenu = new javax.swing.JPanel();
        tb_datapegawai = new javax.swing.JPanel();
        tgllahir = new com.toedter.calendar.JDateChooser();
        Simpan = new javax.swing.JButton();
        ubahsimpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        jeniskelamin = new javax.swing.JComboBox<>();
        jabatan = new javax.swing.JComboBox<>();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        datapegawai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpegawai = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        menu2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        background6 = new javax.swing.JLabel();
        pegawai = new javax.swing.JButton();
        kas = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        laporankas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelkas = new javax.swing.JTable();
        menu4 = new javax.swing.JButton();
        segarkan = new javax.swing.JButton();
        cari1 = new javax.swing.JButton();
        tglcari1 = new com.toedter.calendar.JDateChooser();
        background3 = new javax.swing.JLabel();
        laporanObat = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        laporanobat = new javax.swing.JTable();
        tglcari = new com.toedter.calendar.JDateChooser();
        cari = new javax.swing.JButton();
        segarkan3 = new javax.swing.JButton();
        menulap = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setLayout(null);

        sessionnama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.add(sessionnama);
        sessionnama.setBounds(1030, 10, 220, 20);

        sessionkode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.add(sessionkode);
        sessionkode.setBounds(1030, 40, 210, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/Desain Billin Apotik2.png"))); // NOI18N
        menu.add(jLabel3);
        jLabel3.setBounds(0, 0, 1349, 77);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/LAPORAN PELANGGAN.png"))); // NOI18N
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);
        logout.setBounds(1090, 0, 270, 77);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 77));

        isimenu.setLayout(new java.awt.CardLayout());

        tb_datapegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tb_datapegawai.add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 240, 413, 40));

        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        Simpan.setBorder(null);
        Simpan.setBorderPainted(false);
        Simpan.setContentAreaFilled(false);
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        tb_datapegawai.add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 486, 160, -1));

        ubahsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        ubahsimpan.setBorder(null);
        ubahsimpan.setBorderPainted(false);
        ubahsimpan.setContentAreaFilled(false);
        ubahsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahsimpanActionPerformed(evt);
            }
        });
        tb_datapegawai.add(ubahsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 486, 160, -1));

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/batal.png"))); // NOI18N
        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        tb_datapegawai.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 486, 150, -1));

        nama.setBorder(null);
        tb_datapegawai.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 75, 413, 40));

        alamat.setBorder(null);
        tb_datapegawai.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 325, 413, 40));

        telp.setBorder(null);
        tb_datapegawai.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 408, 413, 40));

        tb_datapegawai.add(jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 486, 413, 40));

        tb_datapegawai.add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 159, 413, 40));

        user.setText("username");
        tb_datapegawai.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 270, 50));

        pass.setText("pass");
        tb_datapegawai.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 270, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/tambahpegawai.png"))); // NOI18N
        tb_datapegawai.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 574));

        isimenu.add(tb_datapegawai, "card3");

        datapegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pegawai", "Nama Pegawai", "Jabatan", "Jenis Kelamin", "Tanggal Lahir", "Alamat", "No. telp"
            }
        ));
        jScrollPane1.setViewportView(tabelpegawai);

        datapegawai.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 920, 410));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah.setBorder(null);
        tambah.setBorderPainted(false);
        tambah.setContentAreaFilled(false);
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        datapegawai.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 130, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        datapegawai.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 150, -1));

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah.setBorderPainted(false);
        ubah.setContentAreaFilled(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        datapegawai.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 260, -1, -1));

        menu2.setText("Menu");
        datapegawai.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 523, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        datapegawai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 574));

        isimenu.add(datapegawai, "card2");

        mainMenu.setPreferredSize(new java.awt.Dimension(1350, 574));
        mainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/main menu pemilik.png"))); // NOI18N
        mainMenu.add(background6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        pegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/DATAPEGAWAI.png"))); // NOI18N
        pegawai.setBorder(null);
        pegawai.setBorderPainted(false);
        pegawai.setContentAreaFilled(false);
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });
        mainMenu.add(pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 290, 200));

        kas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/DATAKAS.png"))); // NOI18N
        kas.setBorder(null);
        kas.setBorderPainted(false);
        kas.setContentAreaFilled(false);
        kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasActionPerformed(evt);
            }
        });
        mainMenu.add(kas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 290, 200));

        obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/LAPORAN OBAT.png"))); // NOI18N
        obat.setBorder(null);
        obat.setBorderPainted(false);
        obat.setContentAreaFilled(false);
        obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatActionPerformed(evt);
            }
        });
        mainMenu.add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 300, 200));

        isimenu.add(mainMenu, "card8");

        laporankas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelkas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No. Transaksi", "Tanggal", "Pelanggan", "Kode Item", "Nama Item", "Jumlah", "Satuan", "Harga", "Sub Total", "Pegawai"
            }
        ));
        jScrollPane2.setViewportView(tabelkas);

        laporankas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 67, 1290, 410));

        menu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu4.setText("Menu");
        laporankas.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 40));

        segarkan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segarkan.setText("Segarkan");
        laporankas.add(segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 100, 40));

        cari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        cari1.setBorder(null);
        cari1.setBorderPainted(false);
        cari1.setContentAreaFilled(false);
        laporankas.add(cari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 55, 30));

        tglcari1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglcari1PropertyChange(evt);
            }
        });
        laporankas.add(tglcari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 30));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        laporankas.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isimenu.add(laporankas, "card5");

        laporanObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laporanobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. ", "Tanggal", "Kode Obat", "Nama Obat", "Satuan", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        jScrollPane6.setViewportView(laporanobat);

        laporanObat.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1280, 410));

        tglcari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglcariPropertyChange(evt);
            }
        });
        laporanObat.add(tglcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 30));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        cari.setBorder(null);
        cari.setBorderPainted(false);
        cari.setContentAreaFilled(false);
        laporanObat.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 55, 30));

        segarkan3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segarkan3.setText("Segarkan");
        laporanObat.add(segarkan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 100, 40));

        menulap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menulap.setText("Menu");
        laporanObat.add(menulap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        laporanObat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isimenu.add(laporanObat, "card9");

        getContentPane().add(isimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 1350, 572));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer1.png"))); // NOI18N
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int close = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?", "Pesan keluar", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
//            System.exit(0);
            view.login login = new login();
            model.model_login model = null;
            try {
                model = new model_login();
            } catch (SQLException ex) {
                Logger.getLogger(menu_karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                new control.user(login, model);
            } catch (SQLException ex) {
                Logger.getLogger(menu_karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatActionPerformed

    private void kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasActionPerformed

    }//GEN-LAST:event_kasActionPerformed

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed

    }//GEN-LAST:event_pegawaiActionPerformed

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked

    }//GEN-LAST:event_tambahMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed

    }//GEN-LAST:event_ubahActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void ubahsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahsimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahsimpanActionPerformed

    private void tglcariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglcariPropertyChange
        if (tglcari.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Tanggal = sdf.format(tglcari.getDate());
            System.out.println(Tanggal);
        }
    }//GEN-LAST:event_tglcariPropertyChange

    private void tglcari1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglcari1PropertyChange
        if (tglcari1.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Tanggal1 = sdf.format(tglcari1.getDate());
            System.out.println(Tanggal1);
        }// TODO add your handling code here:
    }//GEN-LAST:event_tglcari1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_pemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_pemilik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background6;
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JButton cari1;
    private javax.swing.JPanel datapegawai;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel isimenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JComboBox<String> jeniskelamin;
    private javax.swing.JButton kas;
    private javax.swing.JPanel laporanObat;
    private javax.swing.JPanel laporankas;
    private javax.swing.JTable laporanobat;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menu2;
    private javax.swing.JButton menu4;
    private javax.swing.JButton menulap;
    private javax.swing.JTextField nama;
    private javax.swing.JButton obat;
    private javax.swing.JTextField pass;
    private javax.swing.JButton pegawai;
    private javax.swing.JButton segarkan;
    private javax.swing.JButton segarkan3;
    private javax.swing.JLabel sessionkode;
    private javax.swing.JLabel sessionnama;
    private javax.swing.JTable tabelkas;
    private javax.swing.JTable tabelpegawai;
    private javax.swing.JButton tambah;
    private javax.swing.JPanel tb_datapegawai;
    private javax.swing.JTextField telp;
    private com.toedter.calendar.JDateChooser tglcari;
    private com.toedter.calendar.JDateChooser tglcari1;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JButton ubah;
    private javax.swing.JButton ubahsimpan;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}
