/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.model_kasir;
import model.model_login;
import model.obat;

/**
 *
 * @author JUNITA
 */
public class menu_kasir extends javax.swing.JFrame {

    private Object[] header = {"kode obat", "Nama obat", "Jumlah", "Harga"};
    DefaultTableModel tableModel = new DefaultTableModel(null, header);

    public menu_kasir() {
        initComponents();
        tabeltagihan.setModel(tableModel);
        CardLayout cl = (CardLayout) (isiMenu.getLayout());

        isiMenu.add("dataObat", dataObat);
        isiMenu.add("mainMenu", mainMenu);
        isiMenu.add("laporankas", laporankas);
        isiMenu.add("dataTagihan", dataTagihan);
    }

    public void showCard(String key) {
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isiMenu = new javax.swing.JPanel();
        dataObat = new javax.swing.JPanel();
        menu5 = new javax.swing.JButton();
        search1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelUmum = new javax.swing.JTable();
        segarkann = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        background1 = new javax.swing.JLabel();
        background3 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        background6 = new javax.swing.JLabel();
        obat = new javax.swing.JButton();
        tagihan = new javax.swing.JButton();
        kas = new javax.swing.JButton();
        laporankas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelkas = new javax.swing.JTable();
        tglcari = new com.toedter.calendar.JDateChooser();
        cari = new javax.swing.JButton();
        menu4 = new javax.swing.JButton();
        segarkan = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        dataTagihan = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabeltagihan = new javax.swing.JTable();
        cetak3 = new javax.swing.JCheckBox();
        bayar3 = new javax.swing.JTextField();
        total3 = new javax.swing.JLabel();
        kembali4 = new javax.swing.JLabel();
        combonama = new javax.swing.JComboBox<>();
        simpan3 = new javax.swing.JButton();
        jumlah1 = new javax.swing.JTextField();
        hapuss = new javax.swing.JButton();
        menu3 = new javax.swing.JButton();
        txtPelanggan = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        tgl = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        sessionnama = new javax.swing.JLabel();
        sessionkode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isiMenu.setLayout(new java.awt.CardLayout());

        dataObat.setPreferredSize(new java.awt.Dimension(1349, 574));
        dataObat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu5.setText("menu");
        dataObat.add(menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 90, 30));

        search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        search1.setBorder(null);
        search1.setBorderPainted(false);
        search1.setContentAreaFilled(false);
        dataObat.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 18, 62, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Nama Obat");
        dataObat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 220, 30));

        txt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt1.setBorder(null);
        dataObat.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 270, 20));

        tabelUmum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelUmum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Obat", "Satuan", "Isi", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        tabelUmum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUmumMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelUmum);

        dataObat.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        segarkann.setText("Segarkan");
        dataObat.add(segarkann, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer obat.png"))); // NOI18N
        dataObat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 540));

        tabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode", "Satuan", "Stok", "Harga Beli", "Harga Satuan", "Harga Box"
            }
        ));
        jScrollPane3.setViewportView(tabel2);

        dataObat.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1290, 410));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/layer2.png"))); // NOI18N
        dataObat.add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/blank.png"))); // NOI18N
        dataObat.add(background3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataObat, "card2");

        mainMenu.setPreferredSize(new java.awt.Dimension(1350, 574));
        mainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/main menu kasir.png"))); // NOI18N
        mainMenu.add(background6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/obat.png"))); // NOI18N
        obat.setBorder(null);
        obat.setBorderPainted(false);
        obat.setContentAreaFilled(false);
        obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatActionPerformed(evt);
            }
        });
        mainMenu.add(obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 300, 200));

        tagihan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/tagihan.png"))); // NOI18N
        tagihan.setBorder(null);
        tagihan.setBorderPainted(false);
        tagihan.setContentAreaFilled(false);
        tagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagihanActionPerformed(evt);
            }
        });
        mainMenu.add(tagihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 300, 200));

        kas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/kas.png"))); // NOI18N
        kas.setBorder(null);
        kas.setBorderPainted(false);
        kas.setContentAreaFilled(false);
        kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasActionPerformed(evt);
            }
        });
        mainMenu.add(kas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 310, 200));

        isiMenu.add(mainMenu, "card8");

        laporankas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelkas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "No. Transaksi", "Tanggal", "Pelanggan", "Kode Item", "Nama Item", "Jumlah", "Satuan", "Harga", "Sub Total", "Pegawai"
            }
        ));
        jScrollPane4.setViewportView(tabelkas);

        laporankas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 67, 1290, 410));

        tglcari.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglcariPropertyChange(evt);
            }
        });
        laporankas.add(tglcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 270, 30));

        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/cari.png"))); // NOI18N
        cari.setBorder(null);
        cari.setBorderPainted(false);
        cari.setContentAreaFilled(false);
        laporankas.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 55, 30));

        menu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu4.setText("Menu");
        laporankas.add(menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 40));

        segarkan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segarkan.setText("Segarkan");
        laporankas.add(segarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 100, 40));

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        laporankas.add(background4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(laporankas, "card5");

        dataTagihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabeltagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Item", "Nama Item", "Jumlah", "Satuan", "Harga", "Sub Total"
            }
        ));
        jScrollPane8.setViewportView(tabeltagihan);

        dataTagihan.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 750, 250));

        cetak3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cetak3.setSelected(true);
        cetak3.setText("  Cetak");
        cetak3.setContentAreaFilled(false);
        dataTagihan.add(cetak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 100, 40));

        bayar3.setBorder(null);
        dataTagihan.add(bayar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 496, 226, 24));

        total3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataTagihan.add(total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 456, 226, 24));

        kembali4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataTagihan.add(kembali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 535, 226, 24));

        combonama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dataTagihan.add(combonama, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 230, 252, 23));

        simpan3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        simpan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/simpan.png"))); // NOI18N
        simpan3.setBorder(null);
        simpan3.setBorderPainted(false);
        simpan3.setContentAreaFilled(false);
        dataTagihan.add(simpan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1209, 512, 130, 50));

        jumlah1.setBorder(null);
        jumlah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah1ActionPerformed(evt);
            }
        });
        jumlah1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlah1KeyTyped(evt);
            }
        });
        dataTagihan.add(jumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 276, 248, 24));

        hapuss.setText("Hapus");
        dataTagihan.add(hapuss, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        menu3.setText("menu");
        dataTagihan.add(menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 90, 30));

        txtPelanggan.setBorder(null);
        dataTagihan.add(txtPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 62, 260, 24));

        ok.setText("Ok");
        dataTagihan.add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));
        dataTagihan.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 15, 264, 23));

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataTagihan/Desain Billin Apotik2.png"))); // NOI18N
        dataTagihan.add(background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 572));

        isiMenu.add(dataTagihan, "card5");

        getContentPane().add(isiMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1349, 572));

        menu.setLayout(null);

        sessionnama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.add(sessionnama);
        sessionnama.setBounds(1030, 10, 220, 20);

        sessionkode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menu.add(sessionkode);
        sessionkode.setBounds(1030, 40, 210, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/Desain Billin Apotik2.png"))); // NOI18N
        menu.add(jLabel3);
        jLabel3.setBounds(0, 0, 1349, 77);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/logout.png"))); // NOI18N
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);
        logout.setBounds(1125, 0, 225, 77);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 77));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer2.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obatListener(ActionListener listener) {
        obat.addActionListener(listener);
    }

    public void setsessionnama(String sessionAdmin) {
        this.sessionnama.setText(sessionAdmin);
    }

    public void setsessionkode(String sessionAdmin) {
        this.sessionkode.setText(sessionAdmin);
    }

    public void tagihanListener(ActionListener listener) {
        tagihan.addActionListener(listener);
    }

    public void kasListener(ActionListener listener) {
        kas.addActionListener(listener);
    }

    public void SearchObatUmum(ActionListener l) {
        this.search1.addActionListener(l);
    }

    public JTable getTabelObatUmum() {
        return tabelUmum;
    }

    public int getBarisObatUmum() {
        return tabelUmum.getSelectedRow();
    }

    public void carilistener(ActionListener l) {
        this.cari.addActionListener(l);
    }

    String Tanggal;

    public String GetTanggal() {
        return Tanggal;
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelUmum.setModel(tabel);
    }

    public void setTabeltagihan(DefaultTableModel tabel) {
        this.tabeltagihan.setModel(tabel);
    }

    public void tabelListener(MouseListener m) {
        tabelUmum.addMouseListener(m);
    }

    public JTextField settxtsearch1() {
        return txt1;
    }

    public String gettxtsearch1() {
        return txt1.getText();
    }

    public void searchListener(ActionListener e) {
        this.search1.addActionListener(e);
    }

    public void segarkanListener2(ActionListener l) {
        this.segarkann.addActionListener(l);
    }

    public void ok(ActionListener l) {
        this.ok.addActionListener(l);
    }

    public JButton getSearch() {
        return search1;
    }

    public JButton kembaliMenu() {
        return menu3;
    }

    public JButton kembaliMenu5() {
        return menu4;
    }

    public JButton kembaliMenu3() {
        return menu5;
    }

    public void settgl(String value) {
        this.tgl.setText(value);
    }

    public void setPelanggan(String value) {
        this.txtPelanggan.setText(value);
    }

    public void setjumlah(String value) {
        this.jumlah1.setText(value);
    }
    public void setTotal3(String value) {
        this.total3.setText(value);
    }
    public String getNama() {
        return txtPelanggan.getText();
    }

    public double getSelectedJumlah() {
        return Double.parseDouble(tabeltagihan.getValueAt(getRow(), 3).toString());
    }

    public double getSelectedHarga() {
        return Double.parseDouble(tabeltagihan.getValueAt(getRow(), 2).toString());
    }

    public DefaultTableModel getModel() {
        return this.tableModel;
    }

    public void hapusItem(int row) {
        tableModel.removeRow(row);
    }

    public double getSelectedSubTotal() {
        return Double.parseDouble(tabeltagihan.getValueAt(getRow(), 5).toString());
    }

    public int getRow() {
        return tabeltagihan.getSelectedRow();
    }

    public void OKListener(ActionListener listener) {
        ok.addActionListener(listener);
    }

    public void SimpanListener(ActionListener listener) {
        simpan3.addActionListener(listener);
    }

    public void HapusListener(ActionListener listener) {
        hapuss.addActionListener(listener);
    }

    public int getObatSelected() {
        return combonama.getSelectedIndex();
    }

    public void kembalianTagihan(double total) {
        double bayar = Double.parseDouble(bayar3.getText());
        double kembali = bayar - total;
        kembali4.setText(kembali + "");
    }

    public int getjumlah() {
        return Integer.parseInt(jumlah1.getText());
    }

    public void addNamaObat(String id_obat, String namaObat, int jumlah, double harga) {
        int check = check(id_obat);
        if (check == -1) {
            String kolom[] = {
                id_obat,
                namaObat,
                jumlah + "",
                harga + ""};
            tableModel.addRow(kolom);
        } else {
            int jumlahSebelum = Integer.parseInt(tabeltagihan.getValueAt(check, 3).toString());
            tableModel.setValueAt((jumlah + jumlahSebelum) + "", check, 3);
        }
    }

    public int check(String id_obat) {
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if (id_obat.equals(tableModel.getValueAt(i, 0))) {
                return i;
            }
        }
        return -1;
    }

    public String getjmlh() {
        return jumlah1.getText();
    }

    public String gettotal() {
        return total3.getText();
    }

    public String getbayar() {
        return bayar3.getText();
    }

    public String getkmbli() {
        return kembali4.getText();
    }

    public void addObatList(ArrayList<obat> listObat) {
        System.out.println("test list data tagihan");
        DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel<>();
        for (int i = 0; i < listObat.size(); i++) {
            mdl.addElement(listObat.get(i).getnamaobat());
        }
        combonama.setModel(mdl);
    }

    //tagihan
    public int getobatSelected() {
        return combonama.getSelectedIndex();
    }

    public void addItem(String namaobat, String idobat, int jumlah, double harga) {
        int check = check(idobat);
        if (check == -1) {
            String kolom[] = {
                idobat,
                namaobat,
                harga + "",
                jumlah + "",};
            tableModel.addRow(kolom);
        } else {
            int jumlahsebelum = Integer.parseInt(tabeltagihan.getValueAt(check, 3).toString());
            tableModel.setValueAt((jumlah + jumlahsebelum) + "", check, 3);
        }
    }

    public int getJumlah2() {
        return Integer.parseInt(jumlah1.getText());
    }

    public void plusTotal2(double tot2) {
        double totSkg = Double.parseDouble(getTotalBiaya());
        double total = totSkg + tot2;
        total3.setText(total + "");
        
    }

    public void minTotal2(double tot2) {
        double totSkg = Double.parseDouble(gettotal());
        double total = totSkg - tot2;
//        total3.setText(total + "");
        setTotal3(total + "");
    }

    public double getSelectedQty2() {
        return Double.parseDouble(tabeltagihan.getValueAt(getRow(), 3).toString());
    }

    public double getSelectedHarga2() {
        return Double.parseDouble(tabeltagihan.getValueAt(getRow(), 2).toString());
    }

    public void hapusItem2(int row) {
        tableModel.removeRow(row);
    }

    public int getRow2() {
        return tabeltagihan.getSelectedRow();
    }

    public String getBayar() {
        return bayar3.getText();
    }

    public String getTotalBiaya() {
        return total3.getText();
    }

    public void setKembalian(String isi) {
        this.kembali4.setText(isi);
    }

    public String getNamaPelanggan() {
        return txtPelanggan.getText();
    }

    public void btnKembaliListener(ActionListener a) {
        this.menu3.addActionListener(a);
    }

    public void addobatList(ArrayList<obat> listobat) {
        System.out.println("test list obat");
        DefaultComboBoxModel<String> mdl = new DefaultComboBoxModel<>();
        for (int i = 0; i < listobat.size(); i++) {
            mdl.addElement(listobat.get(i).getnamaobat());
        }
        combonama.setModel(mdl);
    }
    private void obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatActionPerformed
        CardLayout cl = (CardLayout) (isiMenu.getLayout());
        cl.show(isiMenu, "");
    }//GEN-LAST:event_obatActionPerformed

    private void tagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagihanActionPerformed

    }//GEN-LAST:event_tagihanActionPerformed

    private void kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasActionPerformed

    }//GEN-LAST:event_kasActionPerformed

    private void tabelUmumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUmumMouseClicked

    }//GEN-LAST:event_tabelUmumMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        int close = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?", "Pesan keluar", JOptionPane.YES_NO_OPTION);

        if (close == JOptionPane.YES_OPTION) {
//            System.exit(0);
            view.login login = new login();
            model.model_login model = null;
            try {
                model = new model_login();
            } catch (SQLException ex) {
                Logger.getLogger(menu_karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                new control.user(login, model);
            } catch (SQLException ex) {
                Logger.getLogger(menu_karyawan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void jumlah1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah1KeyTyped
        char jumlah = evt.getKeyChar();
        if (!(Character.isDigit(jumlah)
                || (jumlah == KeyEvent.VK_BACK_SPACE)
                || (jumlah == KeyEvent.VK_DELETE))) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Harap isi angka");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1KeyTyped

    private void jumlah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah1ActionPerformed

    private void tglcariPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglcariPropertyChange
        if (tglcari.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Tanggal = sdf.format(tglcari.getDate());
            System.out.println(Tanggal);
        }
    }//GEN-LAST:event_tglcariPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background6;
    private javax.swing.JTextField bayar3;
    private javax.swing.JButton cari;
    private javax.swing.JCheckBox cetak3;
    private javax.swing.JComboBox<String> combonama;
    private javax.swing.JPanel dataObat;
    private javax.swing.JPanel dataTagihan;
    private javax.swing.JButton hapuss;
    private javax.swing.JPanel isiMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jumlah1;
    private javax.swing.JButton kas;
    private javax.swing.JLabel kembali4;
    private javax.swing.JPanel laporankas;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JButton menu3;
    private javax.swing.JButton menu4;
    private javax.swing.JButton menu5;
    private javax.swing.JButton obat;
    private javax.swing.JButton ok;
    private javax.swing.JButton search1;
    private javax.swing.JButton segarkan;
    private javax.swing.JButton segarkann;
    private javax.swing.JLabel sessionkode;
    private javax.swing.JLabel sessionnama;
    private javax.swing.JButton simpan3;
    private javax.swing.JTable tabel2;
    private javax.swing.JTable tabelUmum;
    private javax.swing.JTable tabelkas;
    private javax.swing.JTable tabeltagihan;
    private javax.swing.JButton tagihan;
    private javax.swing.JLabel tgl;
    private com.toedter.calendar.JDateChooser tglcari;
    private javax.swing.JLabel total3;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txtPelanggan;
    // End of variables declaration//GEN-END:variables
}
