/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewPemilik;

import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.GridBagLayout;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUNITA
 */
public class menu extends javax.swing.JFrame {

    public menu() {
        initComponents();
        CardLayout cl = (CardLayout) (isimenu.getLayout());

        isimenu.add("datapegawai", datapegawai);
        isimenu.add("tb_datapegawai", tb_datapegawai);
    }

    public void showCard(String key) {
        CardLayout cl = (CardLayout) (isimenu.getLayout());
        cl.show(isimenu, key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void datapegawaiListener(ActionListener listener) {
        pegawai.addActionListener(listener);
    }

    public void datakasListener(ActionListener listener) {
        kas.addActionListener(listener);
    }

    public void laporanObatListener(ActionListener listener) {
        obat.addActionListener(listener);
    }

    public void laporanPelangganListener(ActionListener listener) {
        pelanggan.addActionListener(listener);
    }

    public void logoutListener(ActionListener listener) {
        logout.addActionListener(listener);
    }

    public JButton pegawaiButton() {
        return pegawai;
    }

    //datapegawai
    public JTable gettabelpegawai() {
        return tabelpegawai;
    }

    public int getBaristabelpegawai() {
        return tabelpegawai.getSelectedRow();
    }

    public void setTabel(DefaultTableModel tabel) {
        this.tabelpegawai.setModel(tabel);
    }

    public void tabelpegawai(MouseListener m) {
        tabelpegawai.addMouseListener(m);
    }

    public void TambahpegawaiListener(ActionListener e) {
        this.tambah.addActionListener(e);
    }

    public void UbahpegawaiListener(ActionListener e) {
        this.ubah.addActionListener(e);
    }

    public void HapuspegawaiListener(ActionListener e) {
        this.hapus.addActionListener(e);
    }

    public JButton tambahpegawai() {
        return tambah;
    }

    public JButton getUbahpegawai() {
        return ubah;
    }

    public JButton getHapuspegawai() {
        return hapus;
    }

    public void buttonUbahpegawai(boolean status) {
        this.ubah.setEnabled(status);
    }

    public void buttonHapuspegawai(boolean status) {
        this.hapus.setEnabled(status);
    }

    public void buttonTambahpegawai(boolean status) {
        this.tambah.setEnabled(status);
    }

    //tambah pegawai
    public JDateChooser tanggalLahir() {
        return tgllahir;
    }

    public String getTanggallahir() {

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String tanggal = dateFormat.format(tgllahir.getDate());
        return tanggal;
    }

//        public String getTanggallahir() {
//        Date tgl = tgllahir.getDate();
//        return String.valueOf(tgl);
//    }
    public void setTgllahir(JDateChooser tgllahir) {
        this.tgllahir = tgllahir;
    }

    public void setComboBox_jabatan(String[] jabatan) {
        for (String a : jabatan) {
            this.jabatan.addItem(a);
        }
    }

    public void setComboBox_jeniskelamin(String[] jeniskelamin) {
        for (String a : jeniskelamin) {
            this.jeniskelamin.addItem(a);
        }
    }

    public void setNama(String value) {
        this.nama.setText(value);
    }

    public void setUser(String value) {
        this.user.setText(value);
    }

    public void setPass(String value) {
        this.pass.setText(value);
    }

    public void setAlamat(String value) {
        this.alamat.setText(value);
    }

    public void setNotelp(String value) {
        this.telp.setText(value);
    }

    public JTextField setnamapegawai() {
        return nama;
    }

    public JTextField setalamat() {
        return alamat;
    }

    public JTextField setnotelp() {
        return telp;
    }
    
    public JTextField setUserr() {
        return user;
    }
    
    public JTextField setPassw() {
        return pass;
    }

    public JComboBox getJabatan() {
        return jabatan;
    }

    public JComboBox getJeniskelamin() {
        return jeniskelamin;
    }

    public JButton ubahSimpanpegawai() {
        return ubahsimpan;
    }

    public JButton simpanpegawai() {
        return Simpan;
    }

    public String getNamaPegawai() {
        return nama.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public String getNotelp() {
        return telp.getText();
    }
    
    public String getUser() {
        return user.getText();
    }
    
    public String getPass() {
        return pass.getText();
    }

    public String getValueAt(int baris, int kolom) {
        return (String) this.tabelpegawai.getValueAt(baris, kolom);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        background2 = new javax.swing.JLabel();
        pegawai = new javax.swing.JButton();
        kas = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        pelanggan = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        isimenu = new javax.swing.JPanel();
        tb_datapegawai = new javax.swing.JPanel();
        tgllahir = new com.toedter.calendar.JDateChooser();
        Simpan = new javax.swing.JButton();
        ubahsimpan = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        telp = new javax.swing.JTextField();
        jeniskelamin = new javax.swing.JComboBox<>();
        jabatan = new javax.swing.JComboBox<>();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        background = new javax.swing.JLabel();
        datapegawai = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpegawai = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setLayout(null);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/panelpemilik.png"))); // NOI18N
        menu.add(background2);
        background2.setBounds(0, 0, 1349, 77);

        pegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/LOGOUT_1.png"))); // NOI18N
        pegawai.setBorder(null);
        pegawai.setBorderPainted(false);
        pegawai.setContentAreaFilled(false);
        pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiActionPerformed(evt);
            }
        });
        menu.add(pegawai);
        pegawai.setBounds(0, 0, 270, 77);

        kas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/DATAKAS.png"))); // NOI18N
        kas.setBorder(null);
        kas.setBorderPainted(false);
        kas.setContentAreaFilled(false);
        kas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasActionPerformed(evt);
            }
        });
        menu.add(kas);
        kas.setBounds(270, 0, 270, 77);

        obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/DATAPEGAWAI.png"))); // NOI18N
        obat.setBorder(null);
        obat.setBorderPainted(false);
        obat.setContentAreaFilled(false);
        obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatActionPerformed(evt);
            }
        });
        menu.add(obat);
        obat.setBounds(540, 0, 270, 77);

        pelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/LAPORAN OBAT.png"))); // NOI18N
        pelanggan.setBorder(null);
        pelanggan.setBorderPainted(false);
        pelanggan.setContentAreaFilled(false);
        pelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganActionPerformed(evt);
            }
        });
        menu.add(pelanggan);
        pelanggan.setBounds(810, 0, 270, 77);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/LAPORAN PELANGGAN.png"))); // NOI18N
        logout.setBorder(null);
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        menu.add(logout);
        logout.setBounds(1090, 0, 270, 77);

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 77));

        isimenu.setLayout(new java.awt.CardLayout());

        tb_datapegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tb_datapegawai.add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 240, 413, 40));

        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        Simpan.setBorder(null);
        Simpan.setBorderPainted(false);
        Simpan.setContentAreaFilled(false);
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        tb_datapegawai.add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 486, 160, -1));

        ubahsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/simpan.png"))); // NOI18N
        ubahsimpan.setBorder(null);
        ubahsimpan.setBorderPainted(false);
        ubahsimpan.setContentAreaFilled(false);
        ubahsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahsimpanActionPerformed(evt);
            }
        });
        tb_datapegawai.add(ubahsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 486, 160, -1));

        batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pelanggan/batal.png"))); // NOI18N
        batal.setBorder(null);
        batal.setBorderPainted(false);
        batal.setContentAreaFilled(false);
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        tb_datapegawai.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 486, 150, -1));

        nama.setBorder(null);
        tb_datapegawai.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 75, 413, 40));

        alamat.setBorder(null);
        tb_datapegawai.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 325, 413, 40));

        telp.setBorder(null);
        tb_datapegawai.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 408, 413, 40));

        tb_datapegawai.add(jeniskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 486, 413, 40));

        tb_datapegawai.add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 159, 413, 40));

        user.setText("username");
        tb_datapegawai.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 90, 270, 50));

        pass.setText("pass");
        tb_datapegawai.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 270, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/tambahpegawai.png"))); // NOI18N
        tb_datapegawai.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 574));

        isimenu.add(tb_datapegawai, "card3");

        datapegawai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pegawai", "Nama Pegawai", "Jabatan", "Jenis Kelamin", "Tanggal Lahir", "Alamat", "No. telp"
            }
        ));
        jScrollPane1.setViewportView(tabelpegawai);

        datapegawai.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 920, 470));

        tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/tambah.png"))); // NOI18N
        tambah.setBorder(null);
        tambah.setBorderPainted(false);
        tambah.setContentAreaFilled(false);
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        datapegawai.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 110, 130, -1));

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/hapus.png"))); // NOI18N
        hapus.setBorderPainted(false);
        hapus.setContentAreaFilled(false);
        datapegawai.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 150, -1));

        ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dataObat/ubah.png"))); // NOI18N
        ubah.setBorderPainted(false);
        ubah.setContentAreaFilled(false);
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        datapegawai.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer3.png"))); // NOI18N
        datapegawai.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 574));

        isimenu.add(datapegawai, "card2");

        getContentPane().add(isimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 1350, 572));

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/layer1.png"))); // NOI18N
        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1349, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void pelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelangganActionPerformed

    private void obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatActionPerformed

    private void kasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasActionPerformed

    }//GEN-LAST:event_kasActionPerformed

    private void pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiActionPerformed
        CardLayout cl = (CardLayout) (isimenu.getLayout());
        cl.show(isimenu, "");      // TODO add your handling code here:
    }//GEN-LAST:event_pegawaiActionPerformed

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked

    }//GEN-LAST:event_tambahMouseClicked

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed

    }//GEN-LAST:event_ubahActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimpanActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batalActionPerformed

    private void ubahsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahsimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JButton batal;
    private javax.swing.JPanel datapegawai;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel isimenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jabatan;
    private javax.swing.JComboBox<String> jeniskelamin;
    private javax.swing.JButton kas;
    private javax.swing.JButton logout;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nama;
    private javax.swing.JButton obat;
    private javax.swing.JTextField pass;
    private javax.swing.JButton pegawai;
    private javax.swing.JButton pelanggan;
    private javax.swing.JTable tabelpegawai;
    private javax.swing.JButton tambah;
    private javax.swing.JPanel tb_datapegawai;
    private javax.swing.JTextField telp;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JButton ubah;
    private javax.swing.JButton ubahsimpan;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}
